[colors]
[colors.primary]
background = "#1c2d28"
foreground = "#D4DABA"

[colors.normal]
black   = "#1c2d28"
red     = "#bf616a"
green   = "#6B8C78"
yellow  = "#A5B396"
blue    = "#5C8373"
magenta = "#b48ead"
cyan    = "#768A74"
white   = "#D4DABA"

[colors.bright]
black   = "#5C8373"
red     = "#bf616a"
green   = "#94A88E"
yellow  = "#B2C6A9"
blue    = "#80957B"
magenta = "#b48ead"
cyan    = "#AFBD9B"
white   = "#D4F0DD"

[colors.cursor]
text   = "#1c2d28"
cursor = "#D4DABA"
