# Main background, empty for terminal default, need to be empty if you want transparent background
# 
theme[main_bg]="#1c2d28"

# Main text color
theme[main_fg]="#D4DABA"

# Title color for boxes (Magenta)
theme[title]="#b48ead"

# Highlight color for keyboard shortcuts (Cyan)
theme[hi_fg]="#768A74"

# Background color of selected item in processes box (Cyan)
theme[selected_bg]="#768A74"

# Foreground color of selected item in processes box (Inverted to Dark Base for contrast)
theme[selected_fg]="#1c2d28"

# Color of inactive/disabled text (Dimmed Green/Grey from palette)
theme[inactive_fg]="#94A88E"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#b48ead"

# Box outline and divider line color
theme[cpu_box]="#b48ead"
theme[mem_box]="#5C8373"
theme[net_box]="#5C8373"
theme[proc_box]="#768A74"
theme[div_line]="#6B8C78"

# Gradient for all meters and graphs
theme[temp_start]="#768A74"
theme[temp_mid]="#5C8373"
theme[temp_end]="#6B8C78"

theme[cpu_start]="#768A74"
theme[cpu_mid]="#5C8373"
theme[cpu_end]="#6B8C78"

theme[free_start]="#768A74"
theme[free_mid]="#5C8373"
theme[free_end]="#A5B396"

theme[cached_start]="#768A74"
theme[cached_mid]="#5C8373"
theme[cached_end]="#A5B396"

theme[available_start]="#768A74"
theme[available_mid]="#768A74"
theme[available_end]="#768A74"

theme[used_start]="#6B8C78"
theme[used_mid]="#6B8C78"
theme[used_end]="#6B8C78"

theme[download_start]="#A5B396"
theme[download_mid]="#768A74"
theme[download_end]="#5C8373"

theme[upload_start]="#A5B396"
theme[upload_mid]="#768A74"
theme[upload_end]="#5C8373"
