accent = "#5C8373"
cursor = "#D4DABA"
foreground = "#D4DABA"
background = "#1c2d28"
selection_foreground = "#1c2d28"
selection_background = "#5C8373"

color0 = "#1c2d28"
color1 = "#bf616a"
color2 = "#6B8C78"
color3 = "#A5B396"
color4 = "#5C8373"
color5 = "#b48ead"
color6 = "#768A74"
color7 = "#D4DABA"
color8 = "#5C8373"
color9 = "#bf616a"
color10 = "#94A88E"
color11 = "#B2C6A9"
color12 = "#80957B"
color13 = "#b48ead"
color14 = "#AFBD9B"
color15 = "#D4F0DD"
