# Background and foreground colors
background =#1c2d28
foreground =#D4DABA

# Standard colors
palette = 0=#1c2d28
palette = 1=#bf616a
palette = 2=#6B8C78
palette = 3=#A5B396
palette = 4=#5C8373
palette = 5=#b48ead
palette = 6=#768A74
palette = 7=#D4DABA

# Bright colors
palette = 8=#5C8373
palette = 9=#bf616a
palette = 10=#94A88E
palette = 11=#B2C6A9
palette = 12=#80957B
palette = 13=#b48ead
palette = 14=#AFBD9B
palette = 15=#D4F0DD
