# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

general {
    col.active_border = rgba(bbc5a4ff)
    col.inactive_border = rgb(1c2d28)
    gaps_in = 4
    gaps_out = 5
    border_size = 2
}

decoration {
    rounding = 2
    rounding_power = 3
    shadow {
      enabled = no
      render_power = 8
      range = 10
      color = rgba(55,82,75,1.000)
    }
}

windowrule = match:class ^(vesktop|Vesktop)$, opacity 1.0 override, no_dim on
windowrule = match:class ^(code|VSCode|VSCodium)$, opacity 1.0 override, no_dim on
windowrule = match:class ^(chromium|Chromium|google-chrome|Brave|brave-browser|zen)$, opacity 1.0 override, no_dim on
