$color = rgba(28, 45, 40, 1)
$inner_color = rgba(28, 45, 40, 0.66)
$outer_color = rgba(92, 131, 115, 1)
$font_color = rgba(212, 218, 186, 1)
$placeholder_color = rgba(212, 218, 186, 0.7)
$check_color = rgba(118, 138, 116, 1)
