background            #1c2d28
foreground            #D4DABA

# black
color0  #1c2d28
color8  #5C8373

# red
color1  #bf616a
color9  #bf616a

# green
color2  #6B8C78
color10 #94A88E

# yellow
color3  #A5B396
color11 #B2C6A9

# blue
color4  #5C8373
color12 #80957B

# magenta
color5  #b48ead
color13 #b48ead

# cyan
color6  #768A74
color14 #AFBD9B

# white
color7  #D4DABA
color15 #D4F0DD
